from __future__ import annotations

from dataclasses import dataclass
import math
from typing import Sequence

import numpy as np
import torch
from torch import nn
from torch.distributions import Normal

from .composition import LOGVAR_FLOOR, SIGMA_FLOOR
from .config import PainterConfig
from .env import StrokeAction
from .policies import PassageLatent, Policy
from .spatial_hierarchy import infer_mark_event_belief
from .spatial_state import SpatialCanvasState


POLICY_DESCRIPTOR_DIM = 12
PASSAGE_STEP_DESCRIPTOR_DIM = 14
RELATION_FEATURE_DIM = 7


@dataclass(slots=True)
class PersistentLatentBelief:
    mean: torch.Tensor
    variance: torch.Tensor
    update_count: int = 0

    def diagnostics(self, *, level: str, shape: tuple[int, ...]) -> dict[str, object]:
        variance = torch.clamp(self.variance.detach(), min=1e-12)
        return {
            "level": level,
            "shape": list(shape),
            "dimensions": int(self.mean.numel()),
            "meanNorm": float(torch.linalg.vector_norm(self.mean.detach()).item()),
            "meanStd": float(self.mean.detach().std(unbiased=False).item()),
            "posteriorStdMean": float(torch.sqrt(variance).mean().item()),
            "updateCount": self.update_count,
        }


def policy_descriptor(
    policy_or_actions: Policy | Sequence[StrokeAction],
    config: PainterConfig,
) -> np.ndarray:
    """Deterministic observation of the mark trajectory generated by a policy."""

    actions = policy_or_actions.actions if isinstance(policy_or_actions, Policy) else tuple(policy_or_actions)
    marks = [action for action in actions if not action.stop]
    if not marks:
        descriptor = np.zeros(POLICY_DESCRIPTOR_DIM, dtype=np.float32)
        descriptor[0] = 1.0
        return descriptor

    centers = np.asarray(
        [[0.5 * (action.x0 + action.x1), 0.5 * (action.y0 + action.y1)] for action in marks],
        dtype=np.float64,
    )
    vectors = np.asarray(
        [[action.x1 - action.x0, action.y1 - action.y0] for action in marks],
        dtype=np.float64,
    )
    lengths = np.linalg.norm(vectors, axis=1)
    directions = vectors / np.maximum(lengths[:, None], 1e-8)
    spread = float(np.sqrt(np.square(centers - centers.mean(axis=0)).sum(axis=1).mean()))
    if len(directions) > 1:
        directional_continuity = float(np.sum(directions[:-1] * directions[1:], axis=1).mean())
    else:
        directional_continuity = 1.0
    horizon = float(max(1, config.planning_horizon))
    return np.asarray(
        [
            0.0,
            min(1.0, len(marks) / horizon),
            float(centers[:, 0].mean()),
            float(centers[:, 1].mean()),
            float(directions[:, 0].mean()),
            float(directions[:, 1].mean()),
            float(np.clip(lengths.sum(), 0.0, 2.0) / 2.0),
            float(np.mean([action.width for action in marks])),
            float(np.mean([action.amount for action in marks])),
            float(np.mean([action.tone for action in marks])),
            float(np.clip(spread, 0.0, 1.0)),
            directional_continuity,
        ],
        dtype=np.float32,
    )


def passage_step_descriptor(passage: PassageLatent, step_index: int) -> np.ndarray:
    """Condition for one transition inside a persistent passage.

    The phase variables distinguish an early mark from a late mark without
    changing the slower passage latent itself. This is a transition-model
    condition, not an outcome preference.
    """

    count = max(1, int(passage.stroke_count))
    index = int(np.clip(step_index, 0, count - 1))
    kind_band = float(passage.kind == "band")
    kind_chain = float(passage.kind == "chain")
    # Polyline is the third categorical state: both legacy one-hot entries are
    # zero, while spacing conditionally carries its signed inter-segment turn.
    return np.asarray(
        [
            1.0,
            kind_band,
            kind_chain,
            passage.center_x,
            passage.center_y,
            math.cos(passage.direction),
            math.sin(passage.direction),
            passage.length,
            passage.spacing,
            passage.width,
            passage.amount,
            passage.tone,
            float(index + 1) / count,
            float(count - index - 1) / count,
        ],
        dtype=np.float32,
    )


def policy_passage_steps(policy: Policy) -> tuple[tuple[PassageLatent, int], ...]:
    """Passage latent and passage-relative index for every policy mark."""

    mark_count = len(policy.actions) - 1
    if mark_count <= 0:
        return ()
    if policy.passage is not None:
        return tuple(
            (policy.passage, policy.passage_start_index + offset)
            for offset in range(mark_count)
        )
    if policy.passage_plan is None:
        return ()
    steps: list[tuple[PassageLatent, int]] = []
    for passage in policy.passage_plan.passages:
        steps.extend((passage, index) for index in range(passage.stroke_count))
    return tuple(steps[:mark_count])


def relational_observation_vector(material: np.ndarray, config: PainterConfig) -> np.ndarray:
    """Fixed-slot relational observation derived from a coarse material field."""

    slots, residual_coverage_mass = _relational_region_slots(material, config)
    relations: list[float] = []
    for left in range(config.mark_slot_count):
        for right in range(left + 1, config.mark_slot_count):
            a = slots[left]
            b = slots[right]
            active = float(a[0] * b[0])
            dx = float((b[1] - a[1]) * active)
            dy = float((b[2] - a[2]) * active)
            distance = float(math.hypot(dx, dy))
            spread = max(1e-6, float(a[3] + a[5] + b[3] + b[5]))
            overlap = float(math.exp(-0.5 * distance * distance / spread) * active)
            tone_delta = float((b[9] - a[9]) * active)
            mass_ratio = float(
                np.clip(math.log((float(b[6]) + 1e-6) / (float(a[6]) + 1e-6)), -4.0, 4.0)
                * active
            )
            relations.extend((active, dx, dy, distance, overlap, tone_delta, mass_ratio))
    return np.concatenate(
        [slots.reshape(-1), np.asarray(relations, dtype=np.float32), np.asarray([residual_coverage_mass])]
    ).astype(np.float32)


def _relational_region_slots(
    material: np.ndarray,
    config: PainterConfig,
) -> tuple[np.ndarray, float]:
    """Deterministic region-slot observation, including subdivisions of connected masses."""

    material = np.asarray(material, dtype=np.float32)
    coverage = (
        np.clip(material[5], 0.0, 1.0)
        if material.shape[0] > 5
        else (material[0] >= config.paint_presence_threshold).astype(np.float32)
    )
    active_cells = np.argwhere(coverage >= config.mark_activation_coverage)
    slots = np.zeros((config.mark_slot_count, 12), dtype=np.float32)
    if active_cells.size == 0 or config.mark_slot_count <= 0:
        return slots, float(coverage.mean())

    state = SpatialCanvasState(material=material, logvar=np.full_like(material, -8.0))
    component_count = infer_mark_event_belief(state, config).active_count
    target_cells = max(4.0, coverage.size / float(max(1, 2 * config.mark_slot_count)))
    area_count = int(math.ceil(len(active_cells) / target_cells))
    cluster_count = min(
        config.mark_slot_count,
        len(active_cells),
        max(1, component_count, area_count),
    )
    rows = active_cells[:, 0]
    cols = active_cells[:, 1]
    grid = float(max(1, coverage.shape[0]))
    coordinates = np.stack(((cols + 0.5) / grid, (rows + 0.5) / grid), axis=1).astype(np.float64)
    weights = np.maximum(coverage[rows, cols].astype(np.float64), 1e-6)
    centroid = np.average(coordinates, axis=0, weights=weights)
    first = int(np.argmin(np.square(coordinates - centroid).sum(axis=1)))
    centers = [coordinates[first].copy()]
    while len(centers) < cluster_count:
        distances = np.min(
            np.stack([np.square(coordinates - center).sum(axis=1) for center in centers]),
            axis=0,
        )
        next_index = int(np.argmax(distances * weights))
        centers.append(coordinates[next_index].copy())
    centers_array = np.stack(centers)
    assignments = np.zeros(len(coordinates), dtype=np.int64)
    for _ in range(6):
        distances = np.square(coordinates[:, None, :] - centers_array[None, :, :]).sum(axis=2)
        assignments = distances.argmin(axis=1)
        for index in range(cluster_count):
            selected = assignments == index
            if np.any(selected):
                centers_array[index] = np.average(coordinates[selected], axis=0, weights=weights[selected])

    selected_slots = [
        _region_slot_features(material, coverage, active_cells[assignments == index])
        for index in range(cluster_count)
        if np.any(assignments == index)
    ]
    selected_slots.sort(key=lambda slot: (-float(slot[6]), float(slot[2]), float(slot[1])))
    for index, slot in enumerate(selected_slots[: config.mark_slot_count]):
        slots[index] = slot
    selected_mass = float(sum(float(slot[6]) for slot in selected_slots[: config.mark_slot_count]))
    return slots, max(0.0, float(coverage.mean()) - selected_mass)


def _region_slot_features(
    material: np.ndarray,
    coverage: np.ndarray,
    cells: np.ndarray,
) -> np.ndarray:
    rows = cells[:, 0]
    cols = cells[:, 1]
    grid = float(max(1, coverage.shape[0]))
    weights = np.maximum(coverage[rows, cols].astype(np.float64), 1e-6)
    mass = float(weights.sum())
    x = (cols.astype(np.float64) + 0.5) / grid
    y = (rows.astype(np.float64) + 0.5) / grid
    center_x = float(np.dot(weights, x) / mass)
    center_y = float(np.dot(weights, y) / mass)
    dx = x - center_x
    dy = y - center_y

    def weighted_channel(index: int) -> float:
        if material.shape[0] <= index:
            return 0.0
        return float(np.dot(weights, material[index, rows, cols]) / mass)

    return np.asarray(
        [
            1.0,
            center_x,
            center_y,
            float(np.dot(weights, dx * dx) / mass),
            float(np.dot(weights, dx * dy) / mass),
            float(np.dot(weights, dy * dy) / mass),
            mass / float(coverage.size),
            weighted_channel(0),
            weighted_channel(1),
            weighted_channel(3),
            weighted_channel(4),
            weighted_channel(5) if material.shape[0] > 5 else float(weights.mean()),
        ],
        dtype=np.float32,
    )


def relational_observation_dim(config: PainterConfig) -> int:
    pair_count = config.mark_slot_count * (config.mark_slot_count - 1) // 2
    return config.mark_slot_count * 12 + pair_count * RELATION_FEATURE_DIM + 1


class _LatentTransition(nn.Module):
    def __init__(
        self,
        latent_dim: int,
        context_dim: int,
        hidden_dim: int,
        process_std: float,
        descriptor_dim: int = POLICY_DESCRIPTOR_DIM,
    ) -> None:
        super().__init__()
        self.latent_dim = latent_dim
        self.descriptor_dim = descriptor_dim
        self.process_logvar = 2.0 * math.log(max(1e-4, process_std))
        self.net = nn.Sequential(
            nn.Linear(latent_dim + context_dim + descriptor_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.SiLU(),
            nn.Linear(hidden_dim, 2 * latent_dim),
        )

    def forward(
        self,
        latent: torch.Tensor,
        context: torch.Tensor,
        descriptor: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        delta, raw_logvar = self.net(torch.cat([latent, context, descriptor], dim=-1)).chunk(2, dim=-1)
        mean = latent + 0.25 * torch.tanh(delta)
        logvar = torch.clamp(self.process_logvar + 1.5 * torch.tanh(raw_logvar), -9.0, 1.0)
        return mean, logvar


@dataclass(slots=True)
class PassageTrajectoryPrediction:
    canvas_mean: torch.Tensor
    canvas_logvar: torch.Tensor
    relational_mean: torch.Tensor
    relational_logvar: torch.Tensor
    coarse_material_mean: torch.Tensor
    coarse_material_logvar: torch.Tensor
    kinds: tuple[str, ...]
    step_indices: tuple[int, ...]

    def diagnostics(self) -> dict[str, object]:
        fields = self.coarse_material_mean.detach()
        if fields.shape[0] > 1:
            delta_rms = torch.sqrt(
                torch.square(fields[1:] - fields[:-1]).mean(dim=(1, 2, 3))
            )
            delta_values = delta_rms.cpu().tolist()
        else:
            delta_values = []
        return {
            "stepCount": int(fields.shape[0]),
            "passageKinds": list(self.kinds),
            "passageStepIndices": list(self.step_indices),
            "coarseMaterialFieldShape": list(fields.shape[1:]),
            "coarseMaterialMeanAbs": fields.abs().mean(dim=(1, 2, 3)).cpu().tolist(),
            "coarseMaterialDeltaRms": delta_values,
            "canvasLatentStdMean": torch.exp(0.5 * self.canvas_logvar)
            .mean(dim=1)
            .detach()
            .cpu()
            .tolist(),
            "relationalLatentStdMean": torch.exp(0.5 * self.relational_logvar)
            .mean(dim=1)
            .detach()
            .cpu()
            .tolist(),
            "approximation": (
                "decoded coarse material observations from a passage-conditioned Markov rollout; "
                "the low-level pixel rollout remains the painting-state prediction"
            ),
        }


class HierarchicalCanvasModel(nn.Module):
    """Spatial canvas and relational latent likelihoods with passage transitions."""

    def __init__(self, config: PainterConfig) -> None:
        super().__init__()
        if config.spatial_grid_size % 4 != 0:
            raise ValueError("hierarchical canvas model requires spatial_grid_size divisible by 4")
        self.cfg = config
        self.grid = config.spatial_grid_size
        self.channels = config.spatial_material_channels
        self.latent_channels = config.canvas_latent_channels
        self.latent_grid = self.grid // 4
        self.canvas_latent_dim = self.latent_channels * self.latent_grid * self.latent_grid
        self.relational_dim = relational_observation_dim(config)
        hidden = config.composition_hidden_channels
        relation_hidden = config.hierarchy_hidden_dim

        self.canvas_encoder = nn.Sequential(
            nn.Conv2d(self.channels, hidden, kernel_size=3, stride=2, padding=1),
            nn.SiLU(),
            nn.Conv2d(hidden, 2 * self.latent_channels, kernel_size=3, stride=2, padding=1),
        )
        self.canvas_decoder = nn.Sequential(
            nn.ConvTranspose2d(self.latent_channels, hidden, kernel_size=4, stride=2, padding=1),
            nn.SiLU(),
            nn.ConvTranspose2d(hidden, hidden, kernel_size=4, stride=2, padding=1),
            nn.SiLU(),
            nn.Conv2d(hidden, 2 * self.channels, kernel_size=3, padding=1),
        )
        self.relational_encoder = nn.Sequential(
            nn.Linear(self.relational_dim, relation_hidden),
            nn.SiLU(),
            nn.Linear(relation_hidden, 2 * config.relational_latent_dim),
        )
        self.relational_decoder = nn.Sequential(
            nn.Linear(config.relational_latent_dim, relation_hidden),
            nn.SiLU(),
            nn.Linear(relation_hidden, 2 * self.relational_dim),
        )
        self.canvas_transition = _LatentTransition(
            self.canvas_latent_dim,
            config.relational_latent_dim,
            config.hierarchy_hidden_dim,
            config.canvas_latent_process_std,
        )
        self.relational_transition = _LatentTransition(
            config.relational_latent_dim,
            self.latent_channels,
            config.hierarchy_hidden_dim,
            config.relational_process_std,
        )
        self.passage_canvas_transition = _LatentTransition(
            self.canvas_latent_dim,
            config.relational_latent_dim,
            config.hierarchy_hidden_dim,
            config.canvas_latent_process_std,
            PASSAGE_STEP_DESCRIPTOR_DIM,
        )
        self.passage_relational_transition = _LatentTransition(
            config.relational_latent_dim,
            self.latent_channels,
            config.hierarchy_hidden_dim,
            config.relational_process_std,
            PASSAGE_STEP_DESCRIPTOR_DIM,
        )
        self.canvas_belief: PersistentLatentBelief | None = None
        self.relational_belief: PersistentLatentBelief | None = None
        self.register_buffer("transition_update_count", torch.zeros((), dtype=torch.int64))
        self.register_buffer("passage_trajectory_update_count", torch.zeros((), dtype=torch.int64))
        # Kept outside state_dict so the tensor architecture remains compatible
        # with existing checkpoints. Support is reconstructed from passage-step
        # replay on load and updated only after a kind appears in a training batch.
        self.passage_kind_update_counts = {"band": 0, "chain": 0, "polyline": 0}

    def encode_canvas(self, fields: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        mean, logvar = self.canvas_encoder(fields).chunk(2, dim=1)
        return mean.flatten(1), torch.clamp(logvar.flatten(1), -9.0, 2.0)

    def decode_canvas(self, latent: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        spatial = latent.reshape(-1, self.latent_channels, self.latent_grid, self.latent_grid)
        mean, logvar = self.canvas_decoder(spatial).chunk(2, dim=1)
        return mean, torch.clamp(logvar, LOGVAR_FLOOR, 2.0)

    def relational_observations(self, fields: torch.Tensor) -> torch.Tensor:
        vectors = [
            relational_observation_vector(field, self.cfg)
            for field in fields.detach().cpu().numpy()
        ]
        return torch.tensor(np.stack(vectors), device=fields.device, dtype=fields.dtype)

    def encode_relations(self, observations: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        mean, logvar = self.relational_encoder(observations).chunk(2, dim=-1)
        return mean, torch.clamp(logvar, -9.0, 2.0)

    def decode_relations(self, latent: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        mean, logvar = self.relational_decoder(latent).chunk(2, dim=-1)
        return mean, torch.clamp(logvar, LOGVAR_FLOOR, 2.0)

    @staticmethod
    def _kl_standard(mean: torch.Tensor, logvar: torch.Tensor) -> torch.Tensor:
        return 0.5 * (mean.square() + logvar.exp() - 1.0 - logvar).sum(dim=-1)

    @staticmethod
    def _kl_diagonal(
        q_mean: torch.Tensor,
        q_logvar: torch.Tensor,
        p_mean: torch.Tensor,
        p_logvar: torch.Tensor,
    ) -> torch.Tensor:
        q_var = q_logvar.exp()
        p_var = p_logvar.exp()
        return 0.5 * (
            p_logvar - q_logvar + (q_var + (q_mean - p_mean).square()) / p_var - 1.0
        ).mean(dim=-1)

    def canvas_elbo(self, fields: torch.Tensor, *, sample: bool = False) -> torch.Tensor:
        mean, logvar = self.encode_canvas(fields)
        latent = mean
        if sample:
            latent = mean + torch.exp(0.5 * logvar) * torch.randn_like(mean)
        reconstruction_mean, reconstruction_logvar = self.decode_canvas(latent)
        reconstruction = Normal(
            reconstruction_mean,
            torch.exp(0.5 * reconstruction_logvar),
        ).log_prob(fields).mean(dim=(1, 2, 3))
        cell_count = float(self.channels * self.grid * self.grid)
        return reconstruction - self._kl_standard(mean, logvar) / cell_count

    @staticmethod
    def flat_log_likelihood(fields: torch.Tensor) -> torch.Tensor:
        mean = fields.mean(dim=(2, 3), keepdim=True)
        variance = torch.clamp(
            fields.var(dim=(2, 3), unbiased=False, keepdim=True),
            min=SIGMA_FLOOR**2,
        )
        return Normal(mean, torch.sqrt(variance)).log_prob(fields).mean(dim=(1, 2, 3))

    @torch.no_grad()
    def compression_gap(self, fields: torch.Tensor) -> torch.Tensor:
        return self.canvas_elbo(fields) - self.flat_log_likelihood(fields)

    def training_loss(self, fields: torch.Tensor) -> torch.Tensor:
        canvas_vfe = -self.canvas_elbo(fields, sample=True).mean()
        observations = self.relational_observations(fields)
        mean, logvar = self.encode_relations(observations)
        latent = mean + torch.exp(0.5 * logvar) * torch.randn_like(mean)
        reconstruction_mean, reconstruction_logvar = self.decode_relations(latent)
        relational_log_likelihood = Normal(
            reconstruction_mean,
            torch.exp(0.5 * reconstruction_logvar),
        ).log_prob(observations).mean(dim=-1)
        relational_elbo = relational_log_likelihood - self._kl_standard(mean, logvar) / float(self.relational_dim)
        return canvas_vfe - relational_elbo.mean()

    def reset_persistent_beliefs(self, fields: torch.Tensor) -> None:
        with torch.no_grad():
            canvas_mean, canvas_logvar = self.encode_canvas(fields)
            relations = self.relational_observations(fields)
            relation_mean, relation_logvar = self.encode_relations(relations)
        self.canvas_belief = PersistentLatentBelief(
            canvas_mean[0].detach(),
            canvas_logvar[0].exp().detach(),
        )
        self.relational_belief = PersistentLatentBelief(
            relation_mean[0].detach(),
            relation_logvar[0].exp().detach(),
        )

    def update_persistent_beliefs(self, fields: torch.Tensor, descriptor: torch.Tensor) -> None:
        if self.canvas_belief is None or self.relational_belief is None:
            self.reset_persistent_beliefs(fields)
            return
        with torch.no_grad():
            descriptor = descriptor.reshape(1, -1).to(fields.device, fields.dtype)
            canvas_current = self.canvas_belief.mean.reshape(1, -1)
            relation_current = self.relational_belief.mean.reshape(1, -1)
            canvas_prior_mean, canvas_prior_logvar = self.canvas_transition(
                canvas_current,
                relation_current,
                descriptor,
            )
            canvas_context = canvas_current.reshape(
                1,
                self.latent_channels,
                self.latent_grid,
                self.latent_grid,
            ).mean(dim=(2, 3))
            relation_prior_mean, relation_prior_logvar = self.relational_transition(
                relation_current,
                canvas_context,
                descriptor,
            )
            canvas_prior_logvar = torch.log(
                canvas_prior_logvar.exp() + self.canvas_belief.variance.reshape(1, -1)
            )
            relation_prior_logvar = torch.log(
                relation_prior_logvar.exp() + self.relational_belief.variance.reshape(1, -1)
            )
            observed_canvas_mean, observed_canvas_logvar = self.encode_canvas(fields)
            observed_relations = self.relational_observations(fields)
            observed_relation_mean, observed_relation_logvar = self.encode_relations(observed_relations)
            canvas_mean, canvas_variance = self._precision_fuse(
                canvas_prior_mean,
                canvas_prior_logvar.exp(),
                observed_canvas_mean,
                observed_canvas_logvar.exp(),
            )
            relation_mean, relation_variance = self._precision_fuse(
                relation_prior_mean,
                relation_prior_logvar.exp(),
                observed_relation_mean,
                observed_relation_logvar.exp(),
            )
        self.canvas_belief = PersistentLatentBelief(
            canvas_mean[0].detach(),
            canvas_variance[0].detach(),
            self.canvas_belief.update_count + 1,
        )
        self.relational_belief = PersistentLatentBelief(
            relation_mean[0].detach(),
            relation_variance[0].detach(),
            self.relational_belief.update_count + 1,
        )

    @staticmethod
    def _precision_fuse(
        prior_mean: torch.Tensor,
        prior_variance: torch.Tensor,
        observation_mean: torch.Tensor,
        observation_variance: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        prior_precision = 1.0 / torch.clamp(prior_variance, min=1e-8)
        observation_precision = 1.0 / torch.clamp(observation_variance, min=1e-8)
        variance = 1.0 / (prior_precision + observation_precision)
        mean = variance * (prior_precision * prior_mean + observation_precision * observation_mean)
        return mean, variance

    def predict_passage_trajectory(self, policy: Policy) -> PassageTrajectoryPrediction | None:
        """Roll the slower passage likelihood through every subordinate mark."""

        steps = policy_passage_steps(policy)
        if (
            not self.cfg.passage_trajectory_enabled
            or not steps
            or self.canvas_belief is None
            or self.relational_belief is None
        ):
            return None
        device = next(self.parameters()).device
        canvas_mean = self.canvas_belief.mean.to(device).reshape(1, -1)
        canvas_variance = self.canvas_belief.variance.to(device).reshape(1, -1)
        relation_mean = self.relational_belief.mean.to(device).reshape(1, -1)
        relation_variance = self.relational_belief.variance.to(device).reshape(1, -1)
        canvas_means: list[torch.Tensor] = []
        canvas_logvars: list[torch.Tensor] = []
        relation_means: list[torch.Tensor] = []
        relation_logvars: list[torch.Tensor] = []
        material_means: list[torch.Tensor] = []
        material_logvars: list[torch.Tensor] = []

        for passage, step_index in steps:
            descriptor = torch.tensor(
                passage_step_descriptor(passage, step_index),
                device=device,
                dtype=canvas_mean.dtype,
            ).reshape(1, -1)
            next_canvas_mean, process_canvas_logvar = self.passage_canvas_transition(
                canvas_mean,
                relation_mean,
                descriptor,
            )
            canvas_variance = canvas_variance + process_canvas_logvar.exp()
            canvas_mean = next_canvas_mean
            canvas_logvar = torch.log(torch.clamp(canvas_variance, min=1e-8))
            canvas_context = canvas_mean.reshape(
                1,
                self.latent_channels,
                self.latent_grid,
                self.latent_grid,
            ).mean(dim=(2, 3))
            next_relation_mean, process_relation_logvar = self.passage_relational_transition(
                relation_mean,
                canvas_context,
                descriptor,
            )
            relation_variance = relation_variance + process_relation_logvar.exp()
            relation_mean = next_relation_mean
            relation_logvar = torch.log(torch.clamp(relation_variance, min=1e-8))
            material_mean, material_logvar = self.decode_canvas(canvas_mean)
            canvas_means.append(canvas_mean[0])
            canvas_logvars.append(canvas_logvar[0])
            relation_means.append(relation_mean[0])
            relation_logvars.append(relation_logvar[0])
            material_means.append(material_mean[0])
            material_logvars.append(material_logvar[0])

        return PassageTrajectoryPrediction(
            canvas_mean=torch.stack(canvas_means),
            canvas_logvar=torch.stack(canvas_logvars),
            relational_mean=torch.stack(relation_means),
            relational_logvar=torch.stack(relation_logvars),
            coarse_material_mean=torch.stack(material_means),
            coarse_material_logvar=torch.stack(material_logvars),
            kinds=tuple(passage.kind for passage, _ in steps),
            step_indices=tuple(step_index for _, step_index in steps),
        )

    @torch.no_grad()
    def passage_trajectory_diagnostics(self, policy: Policy) -> dict[str, object] | None:
        prediction = self.predict_passage_trajectory(policy)
        if prediction is None:
            return None
        supported = self.passage_trajectory_supported_steps(policy)
        return {
            **prediction.diagnostics(),
            "transitionUpdates": int(self.passage_trajectory_update_count.item()),
            "supportedSteps": supported,
            "kindUpdateCounts": dict(self.passage_kind_update_counts),
            "likelihoodActiveInEFE": supported == prediction.canvas_mean.shape[0],
        }

    def passage_trajectory_supported_steps(self, policy: Policy) -> int:
        prediction = self.predict_passage_trajectory(policy)
        if prediction is None:
            return 0
        return sum(self.passage_kind_update_counts.get(kind, 0) > 0 for kind in prediction.kinds)

    def passage_trajectory_efe_terms(
        self,
        fields: torch.Tensor,
        policies: Sequence[Policy],
        step_indices: Sequence[int],
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Per-mark hierarchy likelihoods for low-level predicted fields.

        Each field is the low-level rollout after one mark. Its encoded
        posterior is compared with the corresponding prior in the slower
        passage trajectory. Returned KL terms are already precision weighted;
        the validity mask distinguishes absent/untrained passage conditions.
        """

        count = int(fields.shape[0])
        zeros = torch.zeros(count, device=fields.device, dtype=fields.dtype)
        if len(policies) != count or len(step_indices) != count:
            raise ValueError("Passage policies, step indices, and hierarchy observations must align.")
        if count == 0 or int(self.passage_trajectory_update_count.item()) <= 0:
            return zeros, zeros, torch.zeros_like(zeros, dtype=torch.bool)

        canvas_priors: list[torch.Tensor] = []
        canvas_logvars: list[torch.Tensor] = []
        relation_priors: list[torch.Tensor] = []
        relation_logvars: list[torch.Tensor] = []
        valid_values: list[bool] = []
        cache: dict[int, PassageTrajectoryPrediction | None] = {}
        for policy, step_index in zip(policies, step_indices):
            key = id(policy)
            if key not in cache:
                cache[key] = self.predict_passage_trajectory(policy)
            prediction = cache[key]
            index = int(step_index)
            valid = (
                prediction is not None
                and 0 <= index < prediction.canvas_mean.shape[0]
                and self.passage_kind_update_counts.get(prediction.kinds[index], 0) > 0
            )
            valid_values.append(valid)
            if valid:
                assert prediction is not None
                canvas_priors.append(prediction.canvas_mean[index].to(fields.device, fields.dtype))
                canvas_logvars.append(prediction.canvas_logvar[index].to(fields.device, fields.dtype))
                relation_priors.append(prediction.relational_mean[index].to(fields.device, fields.dtype))
                relation_logvars.append(prediction.relational_logvar[index].to(fields.device, fields.dtype))
            else:
                canvas_priors.append(torch.zeros(self.canvas_latent_dim, device=fields.device, dtype=fields.dtype))
                canvas_logvars.append(torch.zeros(self.canvas_latent_dim, device=fields.device, dtype=fields.dtype))
                relation_priors.append(
                    torch.zeros(self.cfg.relational_latent_dim, device=fields.device, dtype=fields.dtype)
                )
                relation_logvars.append(
                    torch.zeros(self.cfg.relational_latent_dim, device=fields.device, dtype=fields.dtype)
                )

        terminal_canvas_mean, terminal_canvas_logvar = self.encode_canvas(fields)
        terminal_relations = self.relational_observations(fields)
        terminal_relation_mean, terminal_relation_logvar = self.encode_relations(terminal_relations)
        valid = torch.tensor(valid_values, device=fields.device, dtype=torch.bool)
        canvas_risk = self.cfg.canvas_latent_transition_precision * self._kl_diagonal(
            terminal_canvas_mean,
            terminal_canvas_logvar,
            torch.stack(canvas_priors),
            torch.stack(canvas_logvars),
        )
        relational_risk = self.cfg.relational_transition_precision * self._kl_diagonal(
            terminal_relation_mean,
            terminal_relation_logvar,
            torch.stack(relation_priors),
            torch.stack(relation_logvars),
        )
        available = valid.to(fields.dtype)
        return canvas_risk * available, relational_risk * available, valid

    def transition_efe_terms(
        self,
        terminal_fields: torch.Tensor,
        descriptors: torch.Tensor,
        policies: Sequence[Policy] | None = None,
        samples_per_policy: int = 1,
        include_structured_passages: bool = True,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        aggregate_trained = int(self.transition_update_count.item()) > 0
        trajectory_trained = int(self.passage_trajectory_update_count.item()) > 0
        if (
            self.canvas_belief is None
            or self.relational_belief is None
            or not (aggregate_trained or trajectory_trained)
        ):
            zeros = torch.zeros(terminal_fields.shape[0], device=terminal_fields.device)
            return zeros, zeros
        descriptors = descriptors.to(terminal_fields.device, terminal_fields.dtype)
        canvas_current = self.canvas_belief.mean.to(terminal_fields.device).reshape(1, -1).expand(
            terminal_fields.shape[0], -1
        )
        relation_current = self.relational_belief.mean.to(terminal_fields.device).reshape(1, -1).expand(
            terminal_fields.shape[0], -1
        )
        canvas_prior_mean, canvas_prior_logvar = self.canvas_transition(
            canvas_current,
            relation_current,
            descriptors,
        )
        canvas_context = canvas_current.reshape(
            -1,
            self.latent_channels,
            self.latent_grid,
            self.latent_grid,
        ).mean(dim=(2, 3))
        relation_prior_mean, relation_prior_logvar = self.relational_transition(
            relation_current,
            canvas_context,
            descriptors,
        )
        canvas_belief_variance = self.canvas_belief.variance.to(terminal_fields.device).reshape(1, -1)
        relation_belief_variance = self.relational_belief.variance.to(terminal_fields.device).reshape(1, -1)
        canvas_prior_logvar = torch.log(canvas_prior_logvar.exp() + canvas_belief_variance)
        relation_prior_logvar = torch.log(relation_prior_logvar.exp() + relation_belief_variance)
        stop = descriptors[:, 0:1] >= 0.5
        canvas_prior_mean = torch.where(stop, canvas_current, canvas_prior_mean)
        relation_prior_mean = torch.where(stop, relation_current, relation_prior_mean)
        canvas_stop_logvar = torch.log(
            canvas_belief_variance + math.exp(self.canvas_transition.process_logvar)
        ).expand_as(canvas_prior_logvar)
        relation_stop_logvar = torch.log(
            relation_belief_variance + math.exp(self.relational_transition.process_logvar)
        ).expand_as(relation_prior_logvar)
        canvas_prior_logvar = torch.where(stop, canvas_stop_logvar, canvas_prior_logvar)
        relation_prior_logvar = torch.where(stop, relation_stop_logvar, relation_prior_logvar)
        likelihood_available = torch.full(
            (terminal_fields.shape[0],),
            aggregate_trained,
            device=terminal_fields.device,
            dtype=torch.bool,
        )
        if policies is not None and not include_structured_passages:
            repeat = max(1, int(samples_per_policy))
            for policy_index, policy in enumerate(policies):
                if policy.passage is not None or policy.passage_plan is not None:
                    start = policy_index * repeat
                    likelihood_available[start : start + repeat] = False
        if policies is not None and trajectory_trained and self.cfg.passage_trajectory_enabled:
            repeat = max(1, int(samples_per_policy))
            if len(policies) * repeat != terminal_fields.shape[0]:
                raise ValueError("Passage policies and terminal hierarchy samples are not aligned.")
            canvas_prior_mean = canvas_prior_mean.clone()
            canvas_prior_logvar = canvas_prior_logvar.clone()
            relation_prior_mean = relation_prior_mean.clone()
            relation_prior_logvar = relation_prior_logvar.clone()
            for policy_index, policy in enumerate(policies):
                if not include_structured_passages:
                    continue
                prediction = self.predict_passage_trajectory(policy)
                if prediction is None:
                    continue
                start = policy_index * repeat
                end = start + repeat
                canvas_prior_mean[start:end] = prediction.canvas_mean[-1].to(terminal_fields.device)
                canvas_prior_logvar[start:end] = prediction.canvas_logvar[-1].to(terminal_fields.device)
                relation_prior_mean[start:end] = prediction.relational_mean[-1].to(terminal_fields.device)
                relation_prior_logvar[start:end] = prediction.relational_logvar[-1].to(terminal_fields.device)
                likelihood_available[start:end] = True
        terminal_canvas_mean, terminal_canvas_logvar = self.encode_canvas(terminal_fields)
        observations = self.relational_observations(terminal_fields)
        terminal_relation_mean, terminal_relation_logvar = self.encode_relations(observations)
        canvas_risk = self.cfg.canvas_latent_transition_precision * self._kl_diagonal(
            terminal_canvas_mean,
            terminal_canvas_logvar,
            canvas_prior_mean,
            canvas_prior_logvar,
        )
        relational_risk = self.cfg.relational_transition_precision * self._kl_diagonal(
            terminal_relation_mean,
            terminal_relation_logvar,
            relation_prior_mean,
            relation_prior_logvar,
        )
        available = likelihood_available.to(terminal_fields.dtype)
        return canvas_risk * available, relational_risk * available

    def transition_training_loss(
        self,
        before_fields: torch.Tensor,
        descriptors: torch.Tensor,
        after_fields: torch.Tensor,
    ) -> torch.Tensor:
        with torch.no_grad():
            before_canvas, _ = self.encode_canvas(before_fields)
            before_relation, _ = self.encode_relations(self.relational_observations(before_fields))
            after_canvas, after_canvas_logvar = self.encode_canvas(after_fields)
            after_relation, after_relation_logvar = self.encode_relations(self.relational_observations(after_fields))
        canvas_prior_mean, canvas_prior_logvar = self.canvas_transition(
            before_canvas,
            before_relation,
            descriptors,
        )
        canvas_context = before_canvas.reshape(
            -1,
            self.latent_channels,
            self.latent_grid,
            self.latent_grid,
        ).mean(dim=(2, 3))
        relation_prior_mean, relation_prior_logvar = self.relational_transition(
            before_relation,
            canvas_context,
            descriptors,
        )
        return (
            self._kl_diagonal(after_canvas, after_canvas_logvar, canvas_prior_mean, canvas_prior_logvar).mean()
            + self._kl_diagonal(
                after_relation,
                after_relation_logvar,
                relation_prior_mean,
                relation_prior_logvar,
            ).mean()
        )

    def passage_trajectory_training_loss(
        self,
        before_fields: torch.Tensor,
        descriptors: torch.Tensor,
        after_fields: torch.Tensor,
    ) -> torch.Tensor:
        canvas_terms, relational_terms = self.passage_trajectory_training_terms(
            before_fields,
            descriptors,
            after_fields,
        )
        return canvas_terms.mean() + relational_terms.mean()

    def passage_trajectory_training_terms(
        self,
        before_fields: torch.Tensor,
        descriptors: torch.Tensor,
        after_fields: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        with torch.no_grad():
            before_canvas, _ = self.encode_canvas(before_fields)
            before_relation, _ = self.encode_relations(self.relational_observations(before_fields))
            after_canvas, after_canvas_logvar = self.encode_canvas(after_fields)
            after_relation, after_relation_logvar = self.encode_relations(self.relational_observations(after_fields))
        canvas_prior_mean, canvas_prior_logvar = self.passage_canvas_transition(
            before_canvas,
            before_relation,
            descriptors,
        )
        canvas_context = canvas_prior_mean.reshape(
            -1,
            self.latent_channels,
            self.latent_grid,
            self.latent_grid,
        ).mean(dim=(2, 3))
        relation_prior_mean, relation_prior_logvar = self.passage_relational_transition(
            before_relation,
            canvas_context,
            descriptors,
        )
        return (
            self._kl_diagonal(after_canvas, after_canvas_logvar, canvas_prior_mean, canvas_prior_logvar),
            self._kl_diagonal(
                after_relation, after_relation_logvar, relation_prior_mean, relation_prior_logvar
            ),
        )

    @staticmethod
    def _cross_entropy_diagonal(
        q_mean: torch.Tensor,
        q_logvar: torch.Tensor,
        p_mean: torch.Tensor,
        p_logvar: torch.Tensor,
    ) -> torch.Tensor:
        return 0.5 * (
            math.log(2.0 * math.pi)
            + p_logvar
            + (q_logvar.exp() + (q_mean - p_mean).square()) / p_logvar.exp()
        ).mean(dim=-1)

    @torch.no_grad()
    def passage_trajectory_evaluation(
        self,
        before_fields: torch.Tensor,
        descriptors: torch.Tensor,
        after_fields: torch.Tensor,
    ) -> dict[str, float]:
        before_canvas, _ = self.encode_canvas(before_fields)
        before_relation, _ = self.encode_relations(self.relational_observations(before_fields))
        after_canvas, after_canvas_logvar = self.encode_canvas(after_fields)
        after_relation, after_relation_logvar = self.encode_relations(self.relational_observations(after_fields))

        def evaluate(condition: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
            canvas_mean, canvas_logvar = self.passage_canvas_transition(
                before_canvas,
                before_relation,
                condition,
            )
            canvas_context = canvas_mean.reshape(
                -1,
                self.latent_channels,
                self.latent_grid,
                self.latent_grid,
            ).mean(dim=(2, 3))
            relation_mean, relation_logvar = self.passage_relational_transition(
                before_relation,
                canvas_context,
                condition,
            )
            return (
                self._kl_diagonal(after_canvas, after_canvas_logvar, canvas_mean, canvas_logvar),
                self._kl_diagonal(after_relation, after_relation_logvar, relation_mean, relation_logvar),
                self._cross_entropy_diagonal(after_canvas, after_canvas_logvar, canvas_mean, canvas_logvar),
                self._cross_entropy_diagonal(
                    after_relation,
                    after_relation_logvar,
                    relation_mean,
                    relation_logvar,
                ),
            )

        canvas_kl, relation_kl, canvas_cross_entropy, relation_cross_entropy = evaluate(descriptors)
        shuffled = descriptors.roll(1, dims=0) if descriptors.shape[0] > 1 else descriptors
        _, _, shuffled_canvas_cross_entropy, shuffled_relation_cross_entropy = evaluate(shuffled)
        conditioned = canvas_cross_entropy + relation_cross_entropy
        shuffled_total = shuffled_canvas_cross_entropy + shuffled_relation_cross_entropy
        return {
            "canvasKLNatsPerDim": float(canvas_kl.mean().item()),
            "relationalKLNatsPerDim": float(relation_kl.mean().item()),
            "canvasCrossEntropyNatsPerDim": float(canvas_cross_entropy.mean().item()),
            "relationalCrossEntropyNatsPerDim": float(relation_cross_entropy.mean().item()),
            "shuffledCrossEntropyNatsPerDim": float(shuffled_total.mean().item()),
            "conditioningGainNatsPerDim": float((shuffled_total - conditioned).mean().item()),
        }

    def mark_transition_update(self) -> None:
        self.transition_update_count.add_(1)

    def mark_passage_trajectory_update(self, descriptors: torch.Tensor | None = None) -> None:
        self.passage_trajectory_update_count.add_(1)
        if descriptors is None:
            # Backward-compatible meaning for legacy tests/callers: the old
            # training corpus contained band and chain passages only.
            self.passage_kind_update_counts["band"] += 1
            self.passage_kind_update_counts["chain"] += 1
            return
        rows = descriptors.detach().cpu().numpy().reshape(-1, PASSAGE_STEP_DESCRIPTOR_DIM)
        for row in rows:
            kind = "band" if row[1] >= 0.5 else "chain" if row[2] >= 0.5 else "polyline"
            self.passage_kind_update_counts[kind] += 1

    def rebuild_passage_kind_support(self, descriptors: Sequence[np.ndarray]) -> None:
        self.passage_kind_update_counts = {"band": 0, "chain": 0, "polyline": 0}
        for descriptor in descriptors:
            row = np.asarray(descriptor, dtype=np.float32).reshape(-1)
            if row.size < 3:
                continue
            kind = "band" if row[1] >= 0.5 else "chain" if row[2] >= 0.5 else "polyline"
            self.passage_kind_update_counts[kind] += 1

    def diagnostics(self) -> dict[str, object]:
        return {
            "canvas": (
                self.canvas_belief.diagnostics(
                    level="persistent spatial canvas posterior q(z_canvas)",
                    shape=(self.latent_channels, self.latent_grid, self.latent_grid),
                )
                if self.canvas_belief is not None
                else None
            ),
            "relational": (
                self.relational_belief.diagnostics(
                    level="persistent relational posterior q(z_relational)",
                    shape=(self.cfg.relational_latent_dim,),
                )
                if self.relational_belief is not None
                else None
            ),
            "markSlots": self.cfg.mark_slot_count,
            "relationalObservationDimensions": self.relational_dim,
            "policyDescriptorDimensions": POLICY_DESCRIPTOR_DIM,
            "transitionUpdates": int(self.transition_update_count.item()),
            "passageTrajectory": {
                "enabled": self.cfg.passage_trajectory_enabled,
                "descriptorDimensions": PASSAGE_STEP_DESCRIPTOR_DIM,
                "transitionUpdates": int(self.passage_trajectory_update_count.item()),
                "kindUpdateCounts": dict(self.passage_kind_update_counts),
                "coarseObservationGrid": [self.grid, self.grid],
                "temporalDepth": "one learned latent transition per subordinate passage mark",
                "posteriorUpdateBoundary": "persistent canvas and relational posteriors update after passage",
                "declaredAs": (
                    "Gaussian passage-conditioned Markov likelihood; its EFE is the sum over marks of "
                    "KL[q(z_t)||p(z_t|z_0,z_passage,phase_1:t)]"
                ),
            },
            "declaredAs": (
                "aggregate and multistep passage-conditioned Gaussian transition likelihoods over persistent "
                "canvas and relational latents; policy EFE contributions are precision-weighted KL terms"
            ),
        }
