"""Helpers used across the package: grids, logging, reproducibility."""

from .export import (
    chapter_data_dir,
    data_paths_for_demo_figure,
    data_paths_for_figure,
    data_paths_for_extra_figure,
    demo_data_dir,
    extra_data_dir,
    extract_animation_data,
    extract_figure_data,
    infer_chapter_from_path,
    infer_demo_slug_from_path,
    infer_extra_topic_from_path,
    save_animation_data,
    save_chapter_data,
    save_demo_data,
    save_extra_data,
    save_figure_data,
)
from .grids import make_grid, make_2d_grid
from .logging import get_logger
from .io import default_data_dir, default_demo_figure_dir, default_figure_dir, ensure_dir
from .notebooks import (
    ExportResult,
    build_notebook,
    chapter_notebook_path,
    default_notebook_dir,
    demo_notebook_path,
    export_all_notebooks,
    export_chapter_notebook,
    export_demo_notebook,
    export_extra_notebook,
    extra_notebook_path,
    read_module_docstring,
    relative_repo_path,
    write_notebook,
)

__all__ = [
    "chapter_data_dir",
    "data_paths_for_demo_figure",
    "data_paths_for_figure",
    "data_paths_for_extra_figure",
    "demo_data_dir",
    "extra_data_dir",
    "make_grid",
    "make_2d_grid",
    "get_logger",
    "default_figure_dir",
    "default_data_dir",
    "default_demo_figure_dir",
    "default_notebook_dir",
    "ensure_dir",
    "build_notebook",
    "chapter_notebook_path",
    "demo_notebook_path",
    "export_all_notebooks",
    "export_chapter_notebook",
    "export_demo_notebook",
    "export_extra_notebook",
    "extra_notebook_path",
    "ExportResult",
    "read_module_docstring",
    "relative_repo_path",
    "write_notebook",
    "extract_animation_data",
    "extract_figure_data",
    "infer_chapter_from_path",
    "infer_demo_slug_from_path",
    "infer_extra_topic_from_path",
    "save_animation_data",
    "save_chapter_data",
    "save_demo_data",
    "save_extra_data",
    "save_figure_data",
]
