"""Active Inference Fundamentals — Python companion to Namjoshi (MIT Press).

The package mirrors the conceptual structure of the book:

    core         — generative process, generative model, exact Bayesian inference
    estimators   — MLE / MAP via analytic and gradient-descent updates
    visualizations — reusable plotting helpers for static and interactive figures
    utils        — grids, logging, reproducibility helpers

The chapter orchestrators in ``chapters/`` are intentionally thin:
they wire configurable components from this package together,
producing the figures and numerical results discussed in the text.
"""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version

try:  # pragma: no cover - metadata lookup is environment dependent
    __version__ = version("active-inference-fundamentals")
except PackageNotFoundError:  # editable / source checkouts
    __version__ = "0.1.0"

from .demo_topics import (
    build_demo,
    demo_topic_slugs,
    demo_topic_spec,
    main_visualize,
)
from .demo_workflows import build_bicycle_demo, build_drone_flight_demo, build_eye_saccades_demo
from .core.compose import (
    Pipeline,
    RunningPosteriorStats,
    running_stats,
)
from .core.continuous_learning import (
    ContinuousHierarchyLayer,
    HierarchicalContinuousModel,
    HierarchicalMessageTerms,
    LearningAttentionComponents,
    LearningAttentionGradient,
    LearningAttentionModel,
    LearningAttentionState,
    hierarchical_continuous_free_energy,
    hierarchical_continuous_grad,
    hierarchical_continuous_grad_fd,
    hierarchical_message_terms,
    learning_attention_free_energy,
    learning_attention_grad,
    learning_attention_grad_fd,
    log_precision_to_precision,
    log_precision_to_variance,
)
from .core.appendix_math import (
    bayes_posterior_from_likelihood,
    dirac_delta_grid,
    dirichlet_mean,
    dirichlet_variance,
    euler_integrate,
    gamma_pdf,
    joint_from_likelihood_prior,
    jensen_gap,
    kronecker_delta,
    marginalize,
    maximum_entropy_distribution,
    mutual_information,
    normalize_categorical,
)
from .core.diagnostics import (
    CalibrationCurve,
    ConvergenceReport,
    OracleAgreement,
    PosteriorPredictiveCheck,
    calibration_curve,
    convergence_report,
    coverage_from_intervals,
    crps_gaussian,
    effective_sample_size,
    gaussian_entropy_mvn,
    gaussian_entropy_univariate,
    gaussian_kl_mvn,
    gaussian_kl_univariate,
    gradient_check,
    gradient_check_vector,
    grid_entropy,
    grid_kl_divergence,
    log_score_gaussian,
    logsumexp,
    normal_ci,
    oracle_agreement,
    posterior_predictive_check,
    standardize,
)
from .core.distributions import (
    diagonal_cov,
    dirac_like_pdf,
    gaussian_log_pdf,
    gaussian_pdf,
    isotropic_cov,
    mahalanobis_squared,
    mvn_log_pdf,
    mvn_pdf,
    mvn_sample,
    uniform_pdf,
)
from .core.ergodic import (
    EntropyBound,
    density_entropy,
    entropy_upper_bound_from_vfe,
    ergodic_density,
    ergodic_ou_trajectory,
)
from .core.bayesian_mechanics import (
    BayesianMechanicsSummary,
    MarkovBlanketFlow,
    bayesian_mechanics_summary,
    blanket_coupling_matrix,
    entropy_vfe_bound_curve,
    phase1_fep_bridge,
    simulate_markov_blanket_flow,
    survival_probability,
    viability_indicator,
)
from .core.factor_graph import (
    FactorGraphChain,
    active_inference_factor_messages,
    backward_smoothing_messages,
    categorical_factor_message,
    forward_backward_smoothing,
    hybrid_model_bridge,
    learning_attention_message,
    marginal_message_passing,
    normalize_message,
    sum_product_chain,
    variational_message_update,
)
from .core.free_energy_forms import (
    FreeEnergyForm,
    action_perception_divergence_form,
    bethe_free_energy_form,
    constrained_bethe_free_energy_form,
    dynamic_vfe_decomposition,
    expected_free_energy_form,
    expected_free_energy_decomposition,
    free_energy_of_future,
    free_energy_of_expected_future,
    free_energy_variant_table,
    generalized_free_energy_form,
    observed_predicted_free_energy,
    renyi_bound,
    renyi_limit_energy,
    static_vfe_decomposition,
)
from .core.model_comparison import (
    bayes_factor,
    bayesian_model_average,
    bayesian_model_expansion,
    bayesian_model_reduction,
    log_bayes_factor,
    model_posterior,
)
from .core.noise import (
    colored_noise_precision,
    finite_difference_derivative,
    sample_colored_noise,
    squared_exponential_covariance,
)
from .core.generative_model import (
    GenerativeModel,
    LinearGaussianModel,
    LinearGaussianMVModel,
)
from .core.generative_process import (
    GenerativeProcess,
    LinearGaussianMVProcess,
    LinearGaussianProcess,
)
from .core.inference import GridBayesianInference, InferenceResult
from .core.lgs import LGSPosterior, LinearGaussianSystem
from .core.predictive_coding import (
    GenerativeFunction,
    GenericFunction,
    LinearFunction,
    PCFreeEnergy,
    PredictiveCodingModel,
    QuadraticFunction,
    pc_curvature_linear,
    pc_free_energy_grad,
    pc_free_energy_grad_fd,
    pc_linear_fixed_point,
    predictive_coding_free_energy,
    sensory_prediction_error,
    state_prediction_error,
)
from .core.generalized_filtering import (
    DynamicStateSpaceModel,
    GeneralizedVectorModel,
    GenericVectorFunction,
    LinearVectorFunction,
    MultivariateDynamicModel,
    VectorFunction,
    correlated_embedding_precision,
    embed_vector_flow,
    flatten_generalized_coordinates,
    gaussian_temporal_covariance,
    generalized_vector_free_energy,
    generalized_vector_free_energy_grad,
    generalized_vector_free_energy_grad_fd,
    generalized_vector_sensory_error,
    generalized_vector_state_error,
    gf_fixed_point_linear,
    gf_free_energy,
    gf_free_energy_grad,
    gf_free_energy_grad_fd,
    gf_sensory_prediction_error,
    gf_state_prediction_error,
    mv_gf_fixed_point_linear,
    mv_gf_free_energy,
    mv_gf_free_energy_grad,
    mv_gf_free_energy_grad_fd,
    unflatten_generalized_coordinates,
)
from .core.generalized_filtering import (
    GeneralizedModel,
    embed_flow,
    generalized_free_energy,
    generalized_free_energy_grad,
    generalized_free_energy_grad_fd,
    generalized_sensory_error,
    generalized_state_error,
    shift_operator,
)
from .core.active_inference import (
    ActiveInferenceAgent,
    MultivariateActiveInferenceAgent,
    action_gradient,
    ai_free_energy,
    multivariate_action_gradient,
    multivariate_ai_free_energy,
    multivariate_perception_flow,
    perception_gradient,
)
from .core.pomdp import (
    EFEComponents,
    PolicyEFETrace,
    POMDPModel,
    accumulate_a_counts,
    accumulate_b_counts,
    accumulate_d_counts,
    action_posterior,
    dirichlet_expected_value,
    discrete_vfe,
    efe_ambiguity,
    efe_risk,
    efe_components,
    efe_with_novelty,
    evaluate_policy,
    evaluate_policy_components,
    expected_A,
    expected_B,
    expected_D,
    expected_free_energy,
    expected_observation,
    forward_filter,
    infer_states,
    is_stochastic_matrix,
    learn_precision,
    novelty_matrix,
    one_hot,
    parameter_novelty,
    policy_posterior,
    policy_posterior_full,
    precision_gradient,
    predict_beliefs,
    predict_state,
    softmax,
)
from .core.pomdp_extensions import (
    SophisticatedInferenceTrace,
    TreePolicySearchResult,
    forget_dirichlet_counts,
    habit_prior_from_counts,
    path_based_policy_scores,
    sophisticated_policy_trace,
    structure_log_evidence,
    structure_posterior,
    time_dependent_preferences,
    tree_policy_search,
    update_preference_counts,
)
from .core.pomdp import (
    FactorialPOMDP,
    HierarchicalPOMDP,
    PrecisionResult,
    factorial_efe,
    factorial_expected_observation,
    factorial_infer_states,
    factorial_likelihood_message,
    factorial_modality_ambiguity,
    factorial_predict_states,
    hierarchical_layer_efe,
    hierarchical_layer_vfe,
    hierarchical_policy_posterior,
)
from .core.variational import (
    GaussianBelief,
    VFEComponents,
    evaluate_q,
    free_energy_bound_gap,
    log_model_evidence,
    surprisal,
    variational_free_energy,
    vfe_c_form,
    vfe_d_form,
    vfe_e_form,
    vfe_g_form,
    vfe_map_form,
    vfe_mle_form,
)
from .core.posterior import (
    Posterior,
    has_credible_interval,
    has_mean_cov,
    posterior_mean,
    posterior_std,
    summarize_posterior,
)
from .core.thermodynamics import (
    ThermodynamicState,
    boltzmann_entropy,
    canonical_probabilities,
    enthalpy,
    expected_energy,
    gibbs_free_energy,
    helmholtz_free_energy,
    vfe_thermodynamic_state,
)
from .core.types import assert_cov, assert_probabilities
from .core.validators import (
    require_1d,
    require_2d,
    require_design_matrix,
    require_finite_array,
    require_in_unit_interval,
    require_int_at_least,
    require_monotone,
    require_non_negative_scalar,
    require_positive_scalar,
    require_same_length,
)
from .estimators.em import (
    FactorAnalysisResult,
    factor_analysis_e_step,
    factor_analysis_m_step,
    fit_factor_analysis,
)
from .estimators.gradient_descent import GradientDescentResult, gradient_descent
from .estimators.linear_regression import (
    BLRPosterior,
    BayesianLinearRegression,
    GDRegressionResult,
    add_intercept,
    gd_linear_regression,
    mle_linear_regression,
)
from .estimators.map import map_analytic_linear, map_loss
from .estimators.mle import mle_analytic_linear, mle_loss
from .estimators.predictive_coding import (
    HierarchicalPCModel,
    HierarchicalPCResult,
    MultivariatePCResult,
    PredictiveCodingResult,
    hierarchical_predictive_coding,
    multivariate_predictive_coding,
    pc_multivariate_linear_fixed_point,
    pc_parameterized_lstsq_oracle,
    predictive_coding_inference,
)
from .estimators.generalized_filtering import (
    DynamicProcess,
    GeneralizedFilterResult,
    MultivariateDynamicProcess,
    MultivariateFilterResult,
    generalized_filter,
    multivariate_generalized_filter,
    simulate_dynamic_process,
    simulate_multivariate_process,
)
from .estimators.generalized_filtering import (
    GeneralizedFilterGCResult,
    GeneralizedVectorFilterResult,
    generalized_filter_gc,
    generalized_measurements_from_series,
    generalized_vector_filter,
)
from .estimators.continuous_learning import (
    LearningAttentionResult,
    simulate_learning_attention,
)
from .estimators.active_inference import (
    ActiveEnvironment,
    ActiveInferenceResult,
    MultivariateActiveEnvironment,
    MultivariateActiveInferenceResult,
    simulate_active_inference,
    simulate_multivariate_active_inference,
)
from .estimators.applications import (
    FaultTolerantControlResult,
    NavigationResult,
    RoboticsTheoryResult,
    SocialInferenceResult,
    robotics_theory_landscape,
    simulate_fault_tolerant_control,
    simulate_robot_navigation,
    simulate_social_inference,
)
from .estimators.pomdp import (
    DirichletParameters,
    GridWorldResult,
    LearningAgentResult,
    LearningResult,
    enumerate_policies,
    HierarchicalResult,
    TwoArmedBanditResult,
    learn_D_vector,
    make_gridworld,
    make_two_armed_bandit,
    precision_policy_sweep,
    simulate_array_learning,
    simulate_hierarchical_agent,
    simulate_learning_agent,
    simulate_pomdp_agent,
    simulate_two_armed_bandit,
)
from .estimators.pomdp_extensions import (
    ParameterForgettingResult,
    PathPolicyResult,
    PreferenceHabitLearningResult,
    StatePreferenceResult,
    StructureLearningResult,
    make_line_world,
    simulate_parameter_forgetting,
    simulate_path_policy_computation,
    simulate_preference_habit_learning,
    simulate_sophisticated_planning,
    simulate_state_preference_schedule,
    simulate_structure_learning,
)
from .source_spine import (
    APPENDICES,
    CHAPTERS,
    SOURCE_PDF_BUILD_DATE,
    SOURCE_PDF_PAGES,
    SOURCE_PDF_PATH,
    SourceAppendix,
    SourceChapter,
    all_section_ids,
    appendix_letters,
    appendix_section_ids,
    chapter_numbers,
    chapter_section_ids,
    has_chapter,
    has_section,
)
from .estimators.variational import (
    CAVIResult,
    CoordinateSearchResult,
    FixedFormResult,
    MeanFieldConfig,
    coordinate_search_vfe,
    fixed_form_vi,
    free_form_cavi,
)
from .utils import (
    chapter_data_dir,
    data_paths_for_demo_figure,
    data_paths_for_figure,
    data_paths_for_extra_figure,
    default_data_dir,
    default_demo_figure_dir,
    default_figure_dir,
    demo_data_dir,
    ensure_dir,
    extra_data_dir,
    extract_animation_data,
    extract_figure_data,
    get_logger,
    make_grid,
    save_animation_data,
    save_chapter_data,
    save_demo_data,
    save_extra_data,
    save_figure_data,
)

# Menu subpackage is imported lazily inside ``run_menu`` so importing
# ``active_inference`` itself stays free of subprocess imports.


def run_menu(argv: list[str] | None = None) -> int:
    """Entry point for the chapter-runner text menu (see ``run.sh``).

    Equivalent to ``python -m active_inference.menu``. Returns a shell
    exit code.
    """
    from .menu import main

    return main(argv)


def run_web(argv: list[str] | None = None) -> int:
    """Entry point for the local web UI (see ``run.sh --web``).

    Equivalent to ``python -m active_inference.web``. Blocks until the
    server is interrupted; returns a shell exit code.
    """
    from .web import main

    return main(argv)

__all__ = [
    "__version__",
    "diagonal_cov",
    "dirac_like_pdf",
    "gaussian_log_pdf",
    "gaussian_pdf",
    "isotropic_cov",
    "mahalanobis_squared",
    "mvn_log_pdf",
    "mvn_pdf",
    "mvn_sample",
    "uniform_pdf",
    "GenerativeProcess",
    "LinearGaussianProcess",
    "LinearGaussianMVProcess",
    "GenerativeModel",
    "LinearGaussianModel",
    "LinearGaussianMVModel",
    "GridBayesianInference",
    "InferenceResult",
    "LinearGaussianSystem",
    "LGSPosterior",
    "BayesianLinearRegression",
    "BLRPosterior",
    "GDRegressionResult",
    "add_intercept",
    "gd_linear_regression",
    "mle_linear_regression",
    "FactorAnalysisResult",
    "fit_factor_analysis",
    "factor_analysis_e_step",
    "factor_analysis_m_step",
    "mle_analytic_linear",
    "mle_loss",
    "map_analytic_linear",
    "map_loss",
    "gradient_descent",
    "GradientDescentResult",
    # Source-spine contract
    "APPENDICES",
    "CHAPTERS",
    "SOURCE_PDF_BUILD_DATE",
    "SOURCE_PDF_PAGES",
    "SOURCE_PDF_PATH",
    "SourceAppendix",
    "SourceChapter",
    "all_section_ids",
    "appendix_letters",
    "appendix_section_ids",
    "chapter_numbers",
    "chapter_section_ids",
    "has_chapter",
    "has_section",
    # Appendices B/C helpers
    "bayes_posterior_from_likelihood",
    "dirac_delta_grid",
    "dirichlet_mean",
    "dirichlet_variance",
    "euler_integrate",
    "gamma_pdf",
    "joint_from_likelihood_prior",
    "jensen_gap",
    "kronecker_delta",
    "marginalize",
    "maximum_entropy_distribution",
    "mutual_information",
    "normalize_categorical",
    "bayes_factor",
    "bayesian_model_average",
    "bayesian_model_expansion",
    "bayesian_model_reduction",
    "log_bayes_factor",
    "model_posterior",
    "colored_noise_precision",
    "finite_difference_derivative",
    "sample_colored_noise",
    "squared_exponential_covariance",
    # Variational free energy (Chapter 4)
    "GaussianBelief",
    "VFEComponents",
    "evaluate_q",
    "variational_free_energy",
    "vfe_g_form",
    "vfe_d_form",
    "vfe_c_form",
    "vfe_e_form",
    "vfe_map_form",
    "vfe_mle_form",
    "log_model_evidence",
    "surprisal",
    "free_energy_bound_gap",
    # Thermodynamic / FEP bridge
    "ThermodynamicState",
    "canonical_probabilities",
    "expected_energy",
    "boltzmann_entropy",
    "helmholtz_free_energy",
    "enthalpy",
    "gibbs_free_energy",
    "vfe_thermodynamic_state",
    # Variational inference algorithms (Chapter 4)
    "coordinate_search_vfe",
    "CoordinateSearchResult",
    "fixed_form_vi",
    "FixedFormResult",
    "free_form_cavi",
    "CAVIResult",
    "MeanFieldConfig",
    # Predictive coding (Chapter 5)
    "GenerativeFunction",
    "LinearFunction",
    "QuadraticFunction",
    "GenericFunction",
    "PredictiveCodingModel",
    "PCFreeEnergy",
    "predictive_coding_free_energy",
    "pc_curvature_linear",
    "pc_free_energy_grad",
    "pc_free_energy_grad_fd",
    "pc_linear_fixed_point",
    "sensory_prediction_error",
    "state_prediction_error",
    "predictive_coding_inference",
    "PredictiveCodingResult",
    "multivariate_predictive_coding",
    "pc_multivariate_linear_fixed_point",
    "pc_parameterized_lstsq_oracle",
    "MultivariatePCResult",
    "hierarchical_predictive_coding",
    "HierarchicalPCModel",
    "HierarchicalPCResult",
    # Chapter 6 — generalized filtering for perception
    "DynamicStateSpaceModel",
    "gf_state_prediction_error",
    "gf_sensory_prediction_error",
    "gf_free_energy",
    "gf_free_energy_grad",
    "gf_free_energy_grad_fd",
    "gf_fixed_point_linear",
    "DynamicProcess",
    "simulate_dynamic_process",
    "generalized_filter",
    "GeneralizedFilterResult",
    "VectorFunction",
    "LinearVectorFunction",
    "GenericVectorFunction",
    "MultivariateDynamicModel",
    "mv_gf_free_energy",
    "mv_gf_free_energy_grad",
    "mv_gf_free_energy_grad_fd",
    "mv_gf_fixed_point_linear",
    "MultivariateDynamicProcess",
    "simulate_multivariate_process",
    "multivariate_generalized_filter",
    "MultivariateFilterResult",
    "shift_operator",
    "embed_flow",
    "gaussian_temporal_covariance",
    "correlated_embedding_precision",
    "flatten_generalized_coordinates",
    "unflatten_generalized_coordinates",
    "GeneralizedModel",
    "generalized_state_error",
    "generalized_sensory_error",
    "generalized_free_energy",
    "generalized_free_energy_grad",
    "generalized_free_energy_grad_fd",
    "generalized_filter_gc",
    "GeneralizedFilterGCResult",
    "GeneralizedVectorModel",
    "embed_vector_flow",
    "generalized_vector_state_error",
    "generalized_vector_sensory_error",
    "generalized_vector_free_energy",
    "generalized_vector_free_energy_grad",
    "generalized_vector_free_energy_grad_fd",
    "generalized_measurements_from_series",
    "generalized_vector_filter",
    "GeneralizedVectorFilterResult",
    # Chapter 8 — learning, attention, hierarchy, and message passing
    "LearningAttentionModel",
    "LearningAttentionState",
    "LearningAttentionComponents",
    "LearningAttentionGradient",
    "log_precision_to_precision",
    "log_precision_to_variance",
    "learning_attention_free_energy",
    "learning_attention_grad",
    "learning_attention_grad_fd",
    "LearningAttentionResult",
    "simulate_learning_attention",
    "ContinuousHierarchyLayer",
    "HierarchicalContinuousModel",
    "HierarchicalMessageTerms",
    "hierarchical_continuous_free_energy",
    "hierarchical_continuous_grad",
    "hierarchical_continuous_grad_fd",
    "hierarchical_message_terms",
    # Chapter 7 — active generalized filtering
    "ActiveInferenceAgent",
    "action_gradient",
    "perception_gradient",
    "ai_free_energy",
    "ActiveEnvironment",
    "simulate_active_inference",
    "ActiveInferenceResult",
    "MultivariateActiveInferenceAgent",
    "multivariate_perception_flow",
    "multivariate_action_gradient",
    "multivariate_ai_free_energy",
    "MultivariateActiveEnvironment",
    "simulate_multivariate_active_inference",
    "MultivariateActiveInferenceResult",
    # Chapter 9 — discrete state-space active inference (POMDP)
    "POMDPModel",
    "EFEComponents",
    "PolicyEFETrace",
    "infer_states",
    "softmax",
    "one_hot",
    "is_stochastic_matrix",
    "predict_state",
    "efe_components",
    "efe_risk",
    "efe_ambiguity",
    "expected_free_energy",
    "evaluate_policy",
    "evaluate_policy_components",
    "policy_posterior",
    "action_posterior",
    "make_gridworld",
    "enumerate_policies",
    "simulate_pomdp_agent",
    "GridWorldResult",
    # Chapter 9 §9.2–9.3 — dynamic filtering + discrete VFE
    "forward_filter",
    "predict_beliefs",
    "expected_observation",
    "discrete_vfe",
    # Chapter 10 — learning the POMDP parameters (Dirichlet)
    "dirichlet_expected_value",
    "expected_A",
    "expected_B",
    "expected_D",
    "accumulate_a_counts",
    "accumulate_b_counts",
    "accumulate_d_counts",
    "novelty_matrix",
    "parameter_novelty",
    "efe_with_novelty",
    "DirichletParameters",
    "LearningResult",
    "LearningAgentResult",
    "learn_D_vector",
    "simulate_array_learning",
    "simulate_learning_agent",
    # Chapter 10 §10.2 — habit + precision policy optimization
    "policy_posterior_full",
    "precision_gradient",
    "learn_precision",
    "PrecisionResult",
    "precision_policy_sweep",
    # Chapter 10 §10.3 — factorial depth
    "FactorialPOMDP",
    "factorial_expected_observation",
    "factorial_likelihood_message",
    "factorial_infer_states",
    "factorial_predict_states",
    "factorial_modality_ambiguity",
    "factorial_efe",
    "make_two_armed_bandit",
    "TwoArmedBanditResult",
    "simulate_two_armed_bandit",
    # Chapter 10 §10.4 — hierarchical depth
    "HierarchicalPOMDP",
    "hierarchical_layer_vfe",
    "hierarchical_layer_efe",
    "hierarchical_policy_posterior",
    "HierarchicalResult",
    "simulate_hierarchical_agent",
    # Chapter 11 — planning extensions
    "SophisticatedInferenceTrace",
    "TreePolicySearchResult",
    "time_dependent_preferences",
    "forget_dirichlet_counts",
    "habit_prior_from_counts",
    "path_based_policy_scores",
    "structure_log_evidence",
    "structure_posterior",
    "tree_policy_search",
    "sophisticated_policy_trace",
    "update_preference_counts",
    "StatePreferenceResult",
    "ParameterForgettingResult",
    "PathPolicyResult",
    "PreferenceHabitLearningResult",
    "StructureLearningResult",
    "make_line_world",
    "simulate_state_preference_schedule",
    "simulate_parameter_forgetting",
    "simulate_path_policy_computation",
    "simulate_preference_habit_learning",
    "simulate_structure_learning",
    "simulate_sophisticated_planning",
    # Chapter 12 — factor-graph extensions
    "FactorGraphChain",
    "active_inference_factor_messages",
    "backward_smoothing_messages",
    "forward_backward_smoothing",
    "hybrid_model_bridge",
    "learning_attention_message",
    "marginal_message_passing",
    # Chapter 13 — application demos
    "FaultTolerantControlResult",
    "NavigationResult",
    "RoboticsTheoryResult",
    "SocialInferenceResult",
    "robotics_theory_landscape",
    "simulate_fault_tolerant_control",
    "simulate_robot_navigation",
    "simulate_social_inference",
    # Chapter 14 — Bayesian mechanics
    "BayesianMechanicsSummary",
    "build_bicycle_demo",
    "build_demo",
    "build_drone_flight_demo",
    "build_eye_saccades_demo",
    "demo_topic_slugs",
    "demo_topic_spec",
    "main_visualize",
    "MarkovBlanketFlow",
    "bayesian_mechanics_summary",
    "blanket_coupling_matrix",
    "entropy_vfe_bound_curve",
    "phase1_fep_bridge",
    "simulate_markov_blanket_flow",
    "survival_probability",
    "viability_indicator",
    # Utilities
    "make_grid",
    "get_logger",
    "default_figure_dir",
    "default_data_dir",
    "default_demo_figure_dir",
    "ensure_dir",
    "chapter_data_dir",
    "data_paths_for_demo_figure",
    "data_paths_for_figure",
    "data_paths_for_extra_figure",
    "demo_data_dir",
    "extra_data_dir",
    "extract_animation_data",
    "extract_figure_data",
    "save_animation_data",
    "save_chapter_data",
    "save_demo_data",
    "save_extra_data",
    "save_figure_data",
    "run_menu",
    "run_web",
    # Composition
    "Pipeline",
    "RunningPosteriorStats",
    "running_stats",
    # Diagnostics
    "CalibrationCurve",
    "PosteriorPredictiveCheck",
    "calibration_curve",
    "coverage_from_intervals",
    "crps_gaussian",
    "effective_sample_size",
    "gaussian_entropy_mvn",
    "gaussian_entropy_univariate",
    "gaussian_kl_mvn",
    "gaussian_kl_univariate",
    "grid_entropy",
    "grid_kl_divergence",
    "log_score_gaussian",
    "logsumexp",
    "normal_ci",
    "posterior_predictive_check",
    "standardize",
    "gradient_check",
    "gradient_check_vector",
    "convergence_report",
    "ConvergenceReport",
    "oracle_agreement",
    "OracleAgreement",
    # Part III extras helpers
    "FreeEnergyForm",
    "expected_free_energy_form",
    "free_energy_of_future",
    "observed_predicted_free_energy",
    "generalized_free_energy_form",
    "bethe_free_energy_form",
    "constrained_bethe_free_energy_form",
    "action_perception_divergence_form",
    "free_energy_of_expected_future",
    "static_vfe_decomposition",
    "dynamic_vfe_decomposition",
    "expected_free_energy_decomposition",
    "renyi_bound",
    "renyi_limit_energy",
    "free_energy_variant_table",
    "normalize_message",
    "categorical_factor_message",
    "sum_product_chain",
    "variational_message_update",
    "EntropyBound",
    "ergodic_density",
    "density_entropy",
    "entropy_upper_bound_from_vfe",
    "ergodic_ou_trajectory",
    # Posterior protocol
    "Posterior",
    "has_credible_interval",
    "has_mean_cov",
    "posterior_mean",
    "posterior_std",
    "summarize_posterior",
    # Type asserts
    "assert_cov",
    "assert_probabilities",
    # Validators
    "require_1d",
    "require_2d",
    "require_design_matrix",
    "require_finite_array",
    "require_in_unit_interval",
    "require_int_at_least",
    "require_monotone",
    "require_non_negative_scalar",
    "require_positive_scalar",
    "require_same_length",
]
