"""Tests for the batch figure-rendering utility."""

from __future__ import annotations

from scripts.run_all_figures import clean_data_dir, clean_output_dir


def test_clean_output_dir_preserves_documentation(tmp_path):
    """Remove generated media while preserving hand-maintained figure docs."""
    chapter = tmp_path / "chapter_08"
    chapter.mkdir()
    readme = chapter / "README.md"
    png = chapter / "example.png"
    gif = chapter / "animation.gif"
    notes = chapter / "notes.txt"

    readme.write_text("# Chapter 8\n", encoding="utf-8")
    png.write_bytes(b"stale png")
    gif.write_bytes(b"stale gif")
    notes.write_text("not generated by the renderer\n", encoding="utf-8")

    assert clean_output_dir(tmp_path) == 2
    assert readme.exists()
    assert notes.exists()
    assert not png.exists()
    assert not gif.exists()


def test_clean_data_dir_preserves_documentation(tmp_path):
    """Remove generated NPZ/JSON data sidecars while preserving data docs."""
    chapter = tmp_path / "chapter_08"
    chapter.mkdir()
    readme = chapter / "README.md"
    agents = chapter / "AGENTS.md"
    npz = chapter / "example.npz"
    manifest = chapter / "example.json"

    readme.write_text("# Chapter 8\n", encoding="utf-8")
    agents.write_text("# Guide\n", encoding="utf-8")
    npz.write_bytes(b"stale npz")
    manifest.write_text("{}", encoding="utf-8")

    assert clean_data_dir(tmp_path) == 2
    assert readme.exists()
    assert agents.exists()
    assert not npz.exists()
    assert not manifest.exists()
